[package]
name = "ui"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = { workspace = true, features = ["fullstack", "router"] }
api = { workspace = true }
dioxus-primitives = { workspace = true }
time = { workspace = true }
tracing = { workspace = true }
dioxus-logger.workspace = true

[features]
default = []
server = ["dioxus/server"]
web = ["dioxus/web", "time/wasm-bindgen"]
