[package]
name = "web"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = { workspace = true, features = ["fullstack", "router"] }
ui = { workspace = true }
api = { workspace = true }
tokio = { workspace = true, optional = true, features = ["full"] }
dotenv = { workspace = true, optional = true }
axum = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }

[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
server = ["dioxus/server", "api/server", "tokio", "dotenv", "axum"]
